name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-dmg2img-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make dmg2img

  build-dmg2img-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: install 
      run: choco install make
    - name: build
      run: make dmg2img